# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-19 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
